services:
  db:
    image: postgres:latest
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: code-together-app
    restart: always
    depends_on:
      - db
    environment:
      ConnectionStrings__MainDb: "Server=db;Port=5432;Username=myuser;Password=mypassword;Database=mydatabase"
    networks:
      - mynetwork
    ports:
      - "7020:7020"

networks:
  mynetwork:

volumes:
  db-data:
    driver: local
