// <auto-generated />
using System;
using CodeTogether.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeTogether.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240730071931_Initial-Create")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.ArgumentCollectionModel", b =>
                {
                    b.Property<Guid>("TC_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TC_PK");

                    b.ToTable("ArgumentCollections");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.ArgumentModel", b =>
                {
                    b.Property<Guid>("OT_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OT_AssemblyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("OT_TC_PK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OT_TypeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OT_PK");

                    b.HasIndex("OT_TC_PK");

                    b.ToTable("Arguments");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.ExecutionConfigurationModel", b =>
                {
                    b.Property<Guid>("EXE_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EXE_FunctionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EXE_ScaffoldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("EXE_TC_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EXE_TO_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EXE_PK");

                    b.HasIndex("EXE_TC_FK");

                    b.HasIndex("EXE_TO_FK");

                    b.ToTable("ExecutionConfigurations");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.ExecutionModel", b =>
                {
                    b.Property<Guid>("EX_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EC_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("EX_PK");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.QuestionModel", b =>
                {
                    b.Property<Guid>("QST_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QST_Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("QST_EXE_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QST_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("QST_PK");

                    b.HasIndex("QST_EXE_FK");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.TestCaseModel", b =>
                {
                    b.Property<Guid>("TST_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TST_Arguments")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TST_ExpectedResponse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TST_IsHidden")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TST_QST_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TST_Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TST_PK");

                    b.HasIndex("TST_QST_FK");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.StmDataModel", b =>
                {
                    b.Property<Guid>("STM_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("STM_Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("STM_Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("STM_PK");

                    b.ToTable("StmData");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.ArgumentModel", b =>
                {
                    b.HasOne("CodeTogether.Data.Models.Questions.ArgumentCollectionModel", "OT_Parent")
                        .WithMany("TC_Types")
                        .HasForeignKey("OT_TC_PK")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OT_Parent");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.ExecutionConfigurationModel", b =>
                {
                    b.HasOne("CodeTogether.Data.Models.Questions.ArgumentCollectionModel", "EXE_InputArguments")
                        .WithMany()
                        .HasForeignKey("EXE_TC_FK")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CodeTogether.Data.Models.Questions.ArgumentModel", "EXE_ReturnArgument")
                        .WithMany()
                        .HasForeignKey("EXE_TO_FK")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("EXE_InputArguments");

                    b.Navigation("EXE_ReturnArgument");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.QuestionModel", b =>
                {
                    b.HasOne("CodeTogether.Data.Models.Questions.ExecutionConfigurationModel", "QST_ExecutionConfigurationModel")
                        .WithMany()
                        .HasForeignKey("QST_EXE_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QST_ExecutionConfigurationModel");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.TestCaseModel", b =>
                {
                    b.HasOne("CodeTogether.Data.Models.Questions.QuestionModel", "TST_Question")
                        .WithMany("QST_TestCases")
                        .HasForeignKey("TST_QST_FK")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TST_Question");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.ArgumentCollectionModel", b =>
                {
                    b.Navigation("TC_Types");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.QuestionModel", b =>
                {
                    b.Navigation("QST_TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
