// <auto-generated />
using System;
using CodeTogether.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeTogether.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeTogether.Data.Models.Game.UserModel", b =>
                {
                    b.Property<Guid>("USR_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("USR_CheckPoints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USR_Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("USR_GM_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("USR_LastHeardFromAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("USR_PasswordHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("USR_PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("USR_UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("USR_PK");

                    b.HasIndex("USR_GM_FK");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.ExecutionConfigurationModel", b =>
                {
                    b.Property<Guid>("EXE_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EXE_ExecutionArgument")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EXE_ExecutionRunnerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EXE_ScaffoldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("EXE_TC_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EXE_TO_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EXE_PK");

                    b.HasIndex("EXE_TC_FK");

                    b.HasIndex("EXE_TO_FK");

                    b.ToTable("ExecutionConfigurations");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.GameModel", b =>
                {
                    b.Property<Guid>("GM_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GM_CreateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GM_GameState")
                        .HasColumnType("int");

                    b.Property<int>("GM_MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("GM_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GM_Private")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GM_StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("GM_PK");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.QuestionModel", b =>
                {
                    b.Property<Guid>("QST_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QST_Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("QST_EXE_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QST_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("QST_PK");

                    b.HasIndex("QST_EXE_FK");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.QuestionSignatureModel", b =>
                {
                    b.Property<Guid>("TC_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TC_TO_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TC_PK");

                    b.ToTable("QuestionSignatures");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.TestCaseModel", b =>
                {
                    b.Property<Guid>("TST_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TST_Arguments")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TST_ExpectedResponse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TST_IsHidden")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TST_QST_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TST_Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TST_PK");

                    b.HasIndex("TST_QST_FK");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.TestRunModel", b =>
                {
                    b.Property<Guid>("TCR_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TCR_ActualResult")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TCR_Exception")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("TCR_Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TCR_TRX_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TCR_TST_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TCR_PK");

                    b.HasIndex("TCR_TST_FK");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.TypeModel", b =>
                {
                    b.Property<Guid>("OT_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OT_AssemblyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OT_TypeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TC_TO_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OT_PK");

                    b.HasIndex("TC_TO_FK");

                    b.ToTable("ArgumentTypes");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.StmDataModel", b =>
                {
                    b.Property<Guid>("STM_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("STM_Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("STM_Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("STM_PK");

                    b.ToTable("StmData");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Submission.SubmissionModel", b =>
                {
                    b.Property<Guid>("SBM_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SBM_Code")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SBM_EXR_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SBM_QST_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SBM_SubmissionTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SBM_PK");

                    b.HasIndex("SBM_EXR_FK");

                    b.HasIndex("SBM_QST_FK");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("CodeTogether.Runner.Engine.ExecutionResultModel", b =>
                {
                    b.Property<Guid>("EXR_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EXR_Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EXR_Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("EXR_TRX_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EXR_PK");

                    b.HasIndex("EXR_TRX_FK");

                    b.ToTable("ExecutionResults");
                });

            modelBuilder.Entity("CodeTogether.Runner.Engine.TestRunExecutionModel", b =>
                {
                    b.Property<Guid>("TRX_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TRX_PK");

                    b.ToTable("TestExecutions");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Game.UserModel", b =>
                {
                    b.HasOne("CodeTogether.Data.Models.Questions.GameModel", "USR_Game")
                        .WithMany("Users")
                        .HasForeignKey("USR_GM_FK");

                    b.Navigation("USR_Game");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.ExecutionConfigurationModel", b =>
                {
                    b.HasOne("CodeTogether.Data.Models.Questions.QuestionSignatureModel", "EXE_InputArguments")
                        .WithMany()
                        .HasForeignKey("EXE_TC_FK")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CodeTogether.Data.Models.Questions.TypeModel", "EXE_ReturnArgument")
                        .WithMany()
                        .HasForeignKey("EXE_TO_FK")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("EXE_InputArguments");

                    b.Navigation("EXE_ReturnArgument");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.QuestionModel", b =>
                {
                    b.HasOne("CodeTogether.Data.Models.Questions.ExecutionConfigurationModel", "QST_ExecutionConfigurationModel")
                        .WithMany()
                        .HasForeignKey("QST_EXE_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QST_ExecutionConfigurationModel");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.TestCaseModel", b =>
                {
                    b.HasOne("CodeTogether.Data.Models.Questions.QuestionModel", "TST_Question")
                        .WithMany("QST_TestCases")
                        .HasForeignKey("TST_QST_FK")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TST_Question");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.TestRunModel", b =>
                {
                    b.HasOne("CodeTogether.Runner.Engine.TestRunExecutionModel", "TCT_Execution")
                        .WithMany("TRX_TestRuns")
                        .HasForeignKey("TCR_TST_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeTogether.Data.Models.Questions.TestCaseModel", "TCR_Parent")
                        .WithMany()
                        .HasForeignKey("TCR_TST_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TCR_Parent");

                    b.Navigation("TCT_Execution");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.TypeModel", b =>
                {
                    b.HasOne("CodeTogether.Data.Models.Questions.QuestionSignatureModel", null)
                        .WithMany("TC_Types")
                        .HasForeignKey("TC_TO_FK");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Submission.SubmissionModel", b =>
                {
                    b.HasOne("CodeTogether.Runner.Engine.ExecutionResultModel", "SBM_Execution")
                        .WithMany()
                        .HasForeignKey("SBM_EXR_FK");

                    b.HasOne("CodeTogether.Data.Models.Questions.QuestionModel", "SBM_Question")
                        .WithMany()
                        .HasForeignKey("SBM_QST_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SBM_Execution");

                    b.Navigation("SBM_Question");
                });

            modelBuilder.Entity("CodeTogether.Runner.Engine.ExecutionResultModel", b =>
                {
                    b.HasOne("CodeTogether.Runner.Engine.TestRunExecutionModel", "EXR_TestRun")
                        .WithMany()
                        .HasForeignKey("EXR_TRX_FK");

                    b.Navigation("EXR_TestRun");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.GameModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.QuestionModel", b =>
                {
                    b.Navigation("QST_TestCases");
                });

            modelBuilder.Entity("CodeTogether.Data.Models.Questions.QuestionSignatureModel", b =>
                {
                    b.Navigation("TC_Types");
                });

            modelBuilder.Entity("CodeTogether.Runner.Engine.TestRunExecutionModel", b =>
                {
                    b.Navigation("TRX_TestRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
